### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Akhilbiju01** [evildevill/instahack#20]
while running this script both in auto and manual I'm running through this error

         [+] Type 1 FOR 1k Passwords
              [+] Type 2 FOR 10K Passwords
              [+] Type 3 FOR 1Million Passwords 

[#] Enter Selected Number: 1

Instagram-Py 2.0.7 ,  Slick Instagram brute force command line tool.
Copyright (C) 2018 The Future Shell , Antony Jr.

[+] Started @ 2020-12-14 15:08:56.566631
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/InstagramPy/InstagramPySession.py", line 87, in __init__
    configuration = json.load(fp)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 8, in <module>
    sys.exit(ExecuteInstagramPy())
  File "/usr/local/lib/python3.8/dist-packages/InstagramPy/__init__.py", line 128, in ExecuteInstagramPy
    session = InstagramPySession(
  File "/usr/local/lib/python3.8/dist-packages/InstagramPy/InstagramPySession.py", line 90, in __init__
    "invalid configuration file at {}".format(configuraion))
NameError: name 'configuraion' is not defined

**Comment by evildevill** [comment]
Bro watch this video tutorial
https://cloudvideo.tv/6rllqe27f44l
